Detect input type
Fbada006/ArtMaker pull request #113
Opened 2024-10-14 10:39 UTC by Fbada006

This PR seeks to remove usages of the motion event and now uses compose types to check for input type. There is also an improvement to ensure that the context is initialised and then reused thus removing the call to creation of the preferences in the `ArtMaker` composable

2024-10-14 10:39 UTC, Fbada006 commented on shared/src/androidMain/kotlin/com/fbada006/shared/ArtMakerInitializer.kt
> +object ArtMakerInitializer {
With this, we can get the context and reuse it in `androidMain`

2024-10-14 10:40 UTC, Fbada006 commented on shared/src/iosMain/kotlin/com/fbada006/shared/data/CreateDataStore.ios.kt
> +actual fun getDataStore(): DataStore<Preferences> {
I have not touched iOS yet

2024-10-15 07:03 UTC, CalebKL requested changes

2024-10-15 07:39 UTC, Fbada006 commented on shared/src/commonMain/kotlin/com/fbada006/shared/composables/ArtMakerDrawScreen.kt
> +                                isDrawing = false
We need it actually. When testing with the stylus, I noticed a bug where the shapes are joined together, ie, the last point of the last shape and the first point of the next shape get linked when using a stylus. This line fixes that issue.

2024-10-15 08:57 UTC, merged