Update The Documentation
Fbada006/ArtMaker pull request #136
Opened 2024-10-30 08:33 UTC by emmanuelmuturia

It fixes #129...

2024-11-04 08:29 UTC, Fbada006 commented
Hey @emmanuelmuturia , I will hijack this and make some more changes (such as the iOS stuff) then merge.

2024-11-04 08:44 UTC, emmanuelmuturia commented
> Hey @emmanuelmuturia , I will hijack this and make some more changes (such as the iOS stuff) then merge.

No worries...

2024-11-04 15:09 UTC, Fbada006 commented
Hey @CalebKL and @emmanuelmuturia , please go through this. As you can see, I have made several changes

2024-11-04 15:18 UTC, Fbada006 approved these changes
Fine with me but I will wait for an extra set of eyes before merging.

2024-11-04 15:18 UTC, Fbada006 commented on artmaker/src/commonMain/kotlin/io/fbada006/artmaker/utils/ExportHelper.kt
> + */
So as you can see @emmanuelmuturia, the approach I have taken is only providing docs to the expect calls. We can think of them as interfaces. As such, we only need to document the base method and not the implementations.

2024-11-04 15:18 UTC, Fbada006 commented on artmaker/src/commonMain/kotlin/io/fbada006/artmaker/customcolorpalette/SelectorIndicator.kt
> + * @param amount Represents the value from which the Half Indicator Thickness will be subtracted from to get the Selector Indicator's [Offset].
You will also notice, @emmanuelmuturia , that I have removed all the names of the methods included in the documentation of the method. That is a bit like defining a word using the word itself.

2024-11-04 20:00 UTC, CalebKL requested changes
@Fbada006 and @emmanuelmuturia, the documentation looks good to me. I only have two pointers. 
1. `@param modifier is the [Modifier]` We could not be too generic here and go with something like, `@param modifier is an optional param to set the layout of the control menu`
2. Since we support IOS and Android now, I think a KMP library can also support Native IOS. We could include this on the README.md. I was going through this [article](https://medium.com/@jvondermarck/developing-with-kotlin-compose-multiplatform-and-integrating-native-ios-libraries-a7b6b795b7ec) and I think its possible

2024-11-04 20:00 UTC, CalebKL commented on artmaker/src/commonMain/kotlin/io/fbada006/artmaker/composables/ArtMakerControlMenu.kt
> + * @param modifier is the modifier
we could change the description to the modifier to something like
"optional param to set the layout of the Control Menu"

2024-11-06 07:49 UTC, Fbada006 commented
The documentation has been updated as requested. As for working natively with iOS, we need to have extra steps to publish the lib to CocoPods, which has not been covered yet as it was not in the original scope of work. Should we go there, then we can update the documentation. An example of how to do that: https://www.marcogomiero.com/posts/2021/kmp-xcframework-official-support/

I will merge this now

2024-11-06 07:49 UTC, merged