Refactor SharedPreferences
Fbada006/ArtMaker pull request #87
Opened 2024-09-12 16:25 UTC by emmanuelmuturia

- Fixes #73 by refactoring all of the ArtMakerSharedPreferences instances to match the project's naming system...

2024-09-12 16:29 UTC, Fbada006 commented
I do not think this task was about renaming, was it? @CalebKL

2024-09-13 08:14 UTC, Fbada006 requested changes
As agreed, this needs more work

2024-09-13 08:20 UTC, emmanuelmuturia commented
> As agreed, this needs more work

Let me share my current changes in a moment...

2024-09-17 06:12 UTC, emmanuelmuturia commented on artmaker/src/main/java/io/artmaker/ArtMakerViewModel.kt
> +                canShowDisableStylusDialog = canShow,
This is noted. I am pushing the latest updates in a moment...

2024-09-17 07:25 UTC, Fbada006 requested changes
Better. Just one more thing to change

2024-09-17 07:25 UTC, Fbada006 commented on artmaker/src/main/java/io/artmaker/ArtMakerViewModel.kt
> +                shouldUseStylusOnly = preferencesManager.getStylusOnlySetting(useStylusOnly = useStylusOnly),
The default values of the preferences should not come from the value being used to set the preferences. Use the default values that were with those preferences before. In the case of stylus setting, eg, the default value was false. the getters from the pref manager do not need to have any paraemeters

2024-09-17 16:44 UTC, Fbada006 approved these changes
Nice work

2024-09-17 17:11 UTC, merged